import { PROJECTS, ROOT, readJson, sandbox, startServer, tool, validId, walk } from '../../lib/core.mjs';import { basename, resolve } from 'node:path';import { buildPlan, detectManager, loadPackage, runScript, smokeHttp } from '../../lib/testing.mjs';
const project=a=>sandbox(PROJECTS,validId(a.project_id,'project_id')),profiles=resolve(ROOT,'.uplex/testing/profiles');
async function profile(id){return readJson(sandbox(profiles,`${validId(id,'profile_id')}.json`))}
async function context(root){const files=(await walk(root,2000)).map(x=>basename(x)),pkg=await loadPackage(root),manager=detectManager(files);return{files,pkg,manager}}
const tools=[
 tool('testing.discover','Detects package manager, configured scripts, test files and test/security configuration; runs nothing.',['testing.read'],{required:['project_id'],properties:{project_id:{type:'string'}}},async a=>{const root=project(a),{files,pkg,manager}=await context(root);return{package_manager:manager,scripts:pkg?.scripts??{},test_files:files.filter(x=>/\.(test|spec)\.[cm]?[jt]sx?$/.test(x)).length,config:{playwright:files.some(x=>x.startsWith('playwright.config.')),cypress:files.some(x=>x.startsWith('cypress.config.')),vitest:files.some(x=>x.startsWith('vitest.config.')),jest:files.some(x=>x.startsWith('jest.config.'))},note:'Discovery does not execute tests or install tools.'}}),
 tool('testing.plan','Builds a verification plan from an allowlisted profile and configured package scripts.',['testing.read'],{required:['project_id','profile_id'],properties:{project_id:{type:'string'},profile_id:{type:'string'}}},async a=>{const root=project(a),{pkg,manager}=await context(root);return buildPlan(pkg,manager,await profile(a.profile_id))}),
 tool('testing.run_script','Runs one package.json script that is referenced by an allowlisted profile.',['testing.execute'],{required:['project_id','profile_id','check_id'],properties:{project_id:{type:'string'},profile_id:{type:'string'},check_id:{type:'string'},timeout_ms:{type:'integer'}}},async a=>{const root=project(a),{pkg,manager}=await context(root),p=await profile(a.profile_id),check=p.checks.find(x=>x.id===a.check_id);if(!check)throw Error('Check não pertence ao perfil aprovado');if(!pkg?.scripts?.[check.script])return{status:'not_configured',check_id:check.id,script:check.script};return{check_id:check.id,kind:check.kind,...await runScript(root,manager,check.script,{timeoutMs:a.timeout_ms??check.timeout_ms})}},{readOnly:false,risk:'medium',evidence:['exit_code','duration_ms','output_hash']}),
 tool('testing.smoke_http','Checks an expected HTTP response on localhost only.',['testing.execute'],{required:['url'],properties:{url:{type:'string'},expected_status:{type:'integer'},body_includes:{type:'string'},timeout_ms:{type:'integer'}}},async a=>smokeHttp(a.url,{expectedStatus:a.expected_status??200,bodyIncludes:a.body_includes??null,timeoutMs:a.timeout_ms??10000}),{risk:'medium',evidence:['http_status','body_hash']})
];startServer({name:'uplex-testing-mcp',version:'1.0.0'},tools);
