import { MCP_ROOT, atomicJson, hash, now, readJson, sandbox, startServer, tool, validId } from '../../lib/core.mjs';import { mkdir, writeFile } from 'node:fs/promises';import { resolve } from 'node:path';
const registryFile=resolve(MCP_ROOT,'sources/source-registry.json'),freshnessFile=resolve(MCP_ROOT,'sources/freshness-policy.json'),quarantine=resolve(MCP_ROOT,'sources/quarantine');
const registry=async()=>(await readJson(registryFile)).sources;
function state(source){if(!source.last_checked_at)return'never_checked';const age=(Date.now()-Date.parse(source.last_checked_at))/86400000;if(age<=source.refresh_days)return'fresh';if(age<=source.refresh_days*2)return'review_due';return'stale'}
function findSource(list,id){const x=list.find(s=>s.id===id);if(!x)throw Error(`Fonte desconhecida: ${id}`);return x}
const tools=[
 tool('sources.list','Lists registered technical sources and their observed freshness.',['sources.read'],{properties:{domain:{type:'string'},status:{type:'string'}}},async a=>(await registry()).filter(x=>(!a.domain||x.domain===a.domain)&&(!a.status||x.status===a.status)).map(x=>({...x,freshness:state(x)}))),
 tool('sources.search','Searches the local source catalog; performs no network request.',['sources.read'],{required:['query'],properties:{query:{type:'string'},domain:{type:'string'},limit:{type:'number'}}},async a=>{const q=a.query.toLowerCase(),limit=Math.min(a.limit??20,100);return(await registry()).filter(x=>(!a.domain||x.domain===a.domain)&&JSON.stringify(x).toLowerCase().includes(q)).slice(0,limit).map(x=>({...x,freshness:state(x)}))}),
 tool('sources.get','Returns one registered source with trust and freshness metadata.',['sources.read'],{required:['source_id'],properties:{source_id:{type:'string'}}},async a=>{const x=findSource(await registry(),validId(a.source_id,'source_id'));return{...x,freshness:state(x)}}),
 tool('sources.check_freshness','Evaluates source freshness from recorded checks without contacting the source.',['sources.read'],{properties:{domain:{type:'string'}}},async a=>{const xs=(await registry()).filter(x=>!a.domain||x.domain===a.domain),items=xs.map(x=>({source_id:x.id,last_checked_at:x.last_checked_at??null,refresh_days:x.refresh_days,freshness:state(x)}));return{items,summary:items.reduce((out,item)=>{(out[item.freshness]??=[]).push(item);return out},{}),policy:await readJson(freshnessFile)}}),
 tool('sources.cite','Builds a structured citation from a registered source; it does not verify a claim.',['sources.read'],{required:['source_id','claim','applicability'],properties:{source_id:{type:'string'},claim:{type:'string'},applicability:{type:'string'},source_version:{type:'string'},content_hash:{type:'string'},confidence:{enum:['confirmed','high','medium','low']}}},async a=>{const x=findSource(await registry(),validId(a.source_id,'source_id'));return{claim:a.claim,source_id:x.id,source_url:x.url,source_version:a.source_version??null,retrieved_at:now(),content_hash:a.content_hash??null,applicability:a.applicability,confidence:a.confidence??'medium',freshness:state(x),warning:state(x)==='never_checked'?'Registry metadata has not verified current source content.':null}}),
 tool('sources.quarantine_document','Stores user-supplied external text in local quarantine with provenance; does not approve or index it.',['sources.ingest'],{required:['source_id','document_id','content'],properties:{source_id:{type:'string'},document_id:{type:'string'},content:{type:'string',maxLength:500000},source_version:{type:'string'},license:{type:'string'},classification:{enum:['public','internal','confidential','restricted']}}},async(a,c)=>{const source=findSource(await registry(),validId(a.source_id,'source_id'));validId(a.document_id,'document_id');if(Buffer.byteLength(a.content,'utf8')>500000)throw Error('Documento excede 500 KB');const dir=sandbox(quarantine,source.id);await mkdir(dir,{recursive:true});const digest=hash(a.content),metadata={document_id:a.document_id,source_id:source.id,state:'quarantined',classification:a.classification??'internal',source_version:a.source_version??null,content_hash:digest,license:a.license??source.license,ingested_at:now(),ingested_by:c.actor??'unknown',reviewed_by:null,limitations:['External content is untrusted and has not been reviewed, approved or indexed.']};await atomicJson(resolve(dir,`${a.document_id}.json`),metadata);await writeFile(resolve(dir,`${a.document_id}.txt`),a.content,'utf8');return metadata},{readOnly:false,risk:'medium',evidence:['content_hash','state']})
];startServer({name:'uplex-sources-mcp',version:'1.0.0'},tools);
