import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { cpus, freemem, homedir, platform, arch, release, totalmem } from 'node:os';
import { readFile } from 'node:fs/promises';
import { basename, resolve } from 'node:path';
import { walk } from './core.mjs';
const execFileAsync=promisify(execFile);

const commands={node:['node',['--version']],npm:['npm',['--version']],pnpm:['pnpm',['--version']],yarn:['yarn',['--version']],bun:['bun',['--version']],git:['git',['--version']],docker:['docker',['--version']],compose:['docker',['compose','version']],python:['python',['--version']],java:['java',['-version']],psql:['psql',['--version']],semgrep:['semgrep',['--version']],gitleaks:['gitleaks',['version']],trivy:['trivy',['--version']],osv:['osv-scanner',['--version']],syft:['syft',['version']]} ;
export async function inspectTools(names=Object.keys(commands)) {const out={};for(const name of names){const spec=commands[name];if(!spec){out[name]={status:'unknown_tool'};continue}const windowsShim=platform()==='win32'&&['npm','pnpm','yarn','bun','semgrep','osv-scanner'].includes(spec[0]);const executable=windowsShim?(process.env.ComSpec??'cmd.exe'):spec[0];const args=windowsShim?['/d','/s','/c',[spec[0],...spec[1]].join(' ')]:spec[1];try{const x=await execFileAsync(executable,args,{windowsHide:true,timeout:5000});out[name]={status:'available',version:`${x.stdout}${x.stderr}`.trim().split(/\r?\n/)[0]}}catch(e){out[name]={status:e.code==='ENOENT'||e.code===9009?'not_installed':'unavailable',reason:e.code==='ENOENT'||e.code===9009?'command_not_found':e.message.split(/\r?\n/)[0]}}}return out}
export function inspectHost(){return{platform:platform(),release:release(),architecture:arch(),home:homedir(),shell:process.env.SHELL??process.env.ComSpec??'unknown',cpu_count:cpus().length,memory_total_bytes:totalmem(),memory_free_bytes:freemem(),node_runtime:process.version}}
export async function detectProjectStack(root){const files=(await walk(root,1500)).map(x=>x.slice(root.length+1).replaceAll('\\','/'));const has=x=>files.includes(x);let packageManager='unknown';if(has('pnpm-lock.yaml'))packageManager='pnpm';else if(has('yarn.lock'))packageManager='yarn';else if(has('bun.lockb')||has('bun.lock'))packageManager='bun';else if(has('package-lock.json'))packageManager='npm';let pkg=null;if(has('package.json'))try{pkg=JSON.parse(await readFile(resolve(root,'package.json'),'utf8'))}catch{}const deps={...(pkg?.dependencies??{}),...(pkg?.devDependencies??{})};const framework=deps.next?'nextjs':deps['@nestjs/core']?'nestjs':deps.vite?'vite':deps.react?'react':pkg?'node':'unknown';const database=deps.prisma||deps['@prisma/client']?'prisma':deps.drizzle||deps['drizzle-orm']?'drizzle':has('docker-compose.yml')||has('docker-compose.yaml')?'inspect_compose':'unknown';return{root:basename(root),package_manager:packageManager,framework,database,scripts:pkg?.scripts??{},infrastructure:{dockerfile:has('Dockerfile'),compose:has('docker-compose.yml')||has('docker-compose.yaml'),vercel:has('vercel.json'),github_actions:files.some(x=>x.startsWith('.github/workflows/'))},files_observed:files.length}}
export function setupPlan(host,stack,tools){const steps=[];const requireTool=(name,why)=>{if(tools[name]?.status!=='available')steps.push({tool:name,status:tools[name]?.status??'not_checked',reason:why,approval_required:true,installation:'Consult the official vendor instructions for the detected operating system; do not install automatically.',verify:commands[name]?[commands[name][0],...commands[name][1]].join(' '):null})};if(stack.framework!=='unknown')requireTool('node','JavaScript runtime required by the detected project');if(stack.package_manager!=='unknown')requireTool(stack.package_manager,`Package manager selected by lockfile: ${stack.package_manager}`);if(stack.infrastructure.dockerfile||stack.infrastructure.compose)requireTool('docker','Container configuration detected');return{host:{platform:host.platform,architecture:host.architecture,shell:host.shell},detected_stack:stack,steps,ready:steps.length===0,limitations:['Version compatibility must be checked against project engine and provider requirements.']}}
