import { spawn } from 'node:child_process';import { platform } from 'node:os';import { readFile } from 'node:fs/promises';import { resolve } from 'node:path';import { hash, now } from './core.mjs';
const safeNames=/^[a-zA-Z0-9:_-]+$/,allowedKinds=new Set(['lint','typecheck','unit','integration','contract','build','e2e','accessibility','security','smoke']);
export async function loadPackage(root){try{return JSON.parse(await readFile(resolve(root,'package.json'),'utf8'))}catch{return null}}
export function detectManager(files){if(files.includes('pnpm-lock.yaml'))return'pnpm';if(files.includes('yarn.lock'))return'yarn';if(files.includes('bun.lock')||files.includes('bun.lockb'))return'bun';if(files.includes('package-lock.json'))return'npm';return'unknown'}
export function commandFor(manager,script){if(!safeNames.test(script))throw Error('Nome de script inválido');if(manager==='npm')return['npm',['run',script]];if(manager==='pnpm')return['pnpm',['run',script]];if(manager==='yarn')return['yarn',[script]];if(manager==='bun')return['bun',['run',script]];throw Error('Package manager não detectado')}
function executable(command){const shim=platform()==='win32'&&['npm','pnpm','yarn','bun'].includes(command);return shim?[process.env.ComSpec??'cmd.exe',['/d','/s','/c']]:[command,[]]}
export async function runScript(root,manager,script,{timeoutMs=120000,maxOutput=100000,env={}}={}){const [command,args]=commandFor(manager,script),[exe,prefix]=executable(command),started=Date.now();return await new Promise(resolveDone=>{let stdout='',stderr='',timedOut=false;const finalArgs=prefix.length?[...prefix,[command,...args].join(' ')]:args,p=spawn(exe,finalArgs,{cwd:root,env:{...process.env,...env},windowsHide:true,stdio:['ignore','pipe','pipe']});const append=(key,value)=>{const text=value.toString();if(key==='out')stdout=(stdout+text).slice(-maxOutput);else stderr=(stderr+text).slice(-maxOutput)};p.stdout.on('data',x=>append('out',x));p.stderr.on('data',x=>append('err',x));const timer=setTimeout(()=>{timedOut=true;p.kill();},Math.min(Math.max(timeoutMs,1000),900000));p.on('error',error=>{clearTimeout(timer);resolveDone(result(null,error.message))});p.on('close',(code,signal)=>{clearTimeout(timer);resolveDone(result(code,signal))});function result(code,signal){const ended=Date.now(),status=timedOut?'blocked':code===0?'passed':'failed',combined=`${stdout}\n${stderr}`;return{execution_id:`test-${started}`,script,command:[command,...args].join(' '),status,exit_code:code,signal:signal??null,timed_out:timedOut,started_at:new Date(started).toISOString(),ended_at:new Date(ended).toISOString(),duration_ms:ended-started,stdout:redact(stdout),stderr:redact(stderr),output_hash:hash(combined),limitations:['Output is truncated to the configured maximum.','A passing script proves only the checks implemented by that script.']}}})}
export function buildPlan(pkg,manager,profile){const scripts=pkg?.scripts??{},checks=[];for(const item of profile.checks??[]){if(!allowedKinds.has(item.kind))throw Error(`Tipo de teste não permitido: ${item.kind}`);const present=Boolean(scripts[item.script]);checks.push({...item,status:present?'available':'not_configured',command:present?commandFor(manager,item.script).flat().join(' '):null})}return{profile_id:profile.id,package_manager:manager,checks,ready:checks.filter(x=>x.required!==false).every(x=>x.status==='available')}}
export function redact(text){return text.replace(/(token|secret|password|api[_-]?key)\s*[=:]\s*[^\s]+/gi,'$1=[REDACTED]').slice(-100000)}
export async function smokeHttp(url,{expectedStatus=200,bodyIncludes=null,timeoutMs=10000}={}){const target=new URL(url);if(!['localhost','127.0.0.1','::1'].includes(target.hostname))throw Error('Smoke HTTP sem aprovação é limitado ao host local');const started=Date.now(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),Math.min(timeoutMs,30000));try{const response=await fetch(target,{signal:controller.signal,redirect:'manual'}),body=(await response.text()).slice(0,10000),passed=response.status===expectedStatus&&(!bodyIncludes||body.includes(bodyIncludes));return{status:passed?'passed':'failed',url:target.toString(),http_status:response.status,expected_status:expectedStatus,body_match:bodyIncludes?body.includes(bodyIncludes):null,duration_ms:Date.now()-started,checked_at:now(),body_hash:hash(body)}}catch(error){return{status:'blocked',url:target.toString(),error:error.name,duration_ms:Date.now()-started,checked_at:now()}}finally{clearTimeout(timer)}}
