import { MCP_ROOT, appendJsonl, now, readJsonl, startServer, tool, validId } from '../../lib/core.mjs';
import { randomUUID as uuid } from 'node:crypto';import { resolve } from 'node:path';
const file=resolve(MCP_ROOT,'data/approvals.jsonl');
const latest=async()=>{const m=new Map();for(const x of await readJsonl(file))m.set(x.approval_id,x);return m};
const tools=[
 tool('approval.request','Registra solicitação de aprovação.',['approval.write'],{required:['project_id','action','risk_summary'],properties:{project_id:{type:'string'},action:{type:'string'},risk_summary:{type:'string'},ttl_minutes:{type:'number'}}},async(a,c)=>{validId(a.project_id,'project_id');const x={approval_id:`apr-${uuid()}`,project_id:a.project_id,action:a.action,risk_summary:a.risk_summary,requested_by:c.actor??'unknown',status:'pending',single_use:true,created_at:now(),valid_until:new Date(Date.now()+(a.ttl_minutes??30)*60000).toISOString()};await appendJsonl(file,x);return x},{readOnly:false,risk:'medium'}),
 tool('approval.decide','Aprova ou rejeita solicitação.',['approval.write'],{required:['approval_id','decision'],properties:{approval_id:{type:'string'},decision:{enum:['approved','rejected']}}},async(a,c)=>{const x=(await latest()).get(a.approval_id);if(!x||x.status!=='pending')throw Error('Aprovação indisponível');const y={...x,status:a.decision,decided_by:c.actor??'unknown',decided_at:now()};await appendJsonl(file,y);return y},{readOnly:false,risk:'high'}),
 tool('approval.consume','Consome aprovação válida de uso único.',['approval.consume'],{required:['approval_id','action','project_id'],properties:{approval_id:{type:'string'},action:{type:'string'},project_id:{type:'string'}}},async a=>{const x=(await latest()).get(a.approval_id);if(!x||x.status!=='approved'||x.action!==a.action||x.project_id!==a.project_id||Date.parse(x.valid_until)<Date.now())throw Error('Aprovação inválida ou expirada');const y={...x,status:'consumed',consumed_at:now()};await appendJsonl(file,y);return y},{readOnly:false,risk:'high'})
];startServer({name:'uplex-approval-mcp',version:'1.0.0'},tools);
